# ★Numpyについて

In [1]:
# インポート
import numpy as np

### 1次元配列

In [2]:
a = np.array([1,2,3])
a 

array([1, 2, 3])

In [3]:
print(a)

# 型
print(type(a))

# 一次元配列で要素が3つある
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


### 2次元配列

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 2行3列の配列
print(b.shape)

(2, 3)


### 変形

In [6]:
c1 = np.array(range(6))
c1

array([0, 1, 2, 3, 4, 5])

In [7]:
# 2行3列の配列に変形
c2 = c1.reshape(2, 3) # ((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
# もとに戻す
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [9]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [10]:
# お試し 変わらなかった…
cc1 = np.array([[1, 2, 3], [4, 5, 6]])
print("ravel:", cc1.ravel())
print("flatten:", cc1.flatten())

ravel: [1 2 3 4 5 6]
flatten: [1 2 3 4 5 6]


### データ型

In [11]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [12]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [13]:
d.dtype

dtype('int16')

In [14]:
# 型の変更
d.astype(np.float16)

array([1., 2.], dtype=float16)

### インデックスとスライス

In [15]:
a = np.array([1,2,3])
a[0]

1

In [16]:
a[1:]

array([2, 3])

In [17]:
a[-1]

3

In [19]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b[1]

array([4, 5, 6])

In [20]:
b[1,0]

4

In [21]:
b[1][0]

4

In [23]:
# 列を取り出す。この場合は3列目を取り出している。
b[:, 2]

array([3, 6])

In [26]:
# 行の取り出し
b[1, :]

array([4, 5, 6])

In [29]:
# 1行目の配列をスライスで取り出す。
b[0, 1:]

array([2, 3])

In [31]:
# すべての行0と2番目の要素を取り出す。
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

### データ再代入

In [33]:
a = np.array([1,2,3])
a[2] = 4
a

array([1, 2, 4])

In [34]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [36]:
# 列の再代入
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

### 深いコピー

In [37]:
a = np.array([1,2,3])
a1 = a
a

array([1, 2, 3])

In [39]:
a1[1] = 5
a1

array([1, 5, 3])

In [46]:
# 通常の代入では代入先で値を変更すると、コピー元も変わってしまう。
a

array([1, 5, 3])

In [40]:
a2 = a.copy()
a2

array([1, 5, 3])

In [42]:
# copy()を用いることで、値を変更してもコピー元の値は変わらない。
a2[0] = 100
a2

array([100,   5,   3])

In [47]:
a

array([1, 5, 3])

In [48]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [56]:
# ravelはコピー元も変わるが、flattenはコピー元は変わらない。
print("ravel:", c3)
print("flatten:", c4)
print("original:\n", c2)

ravel: [6 1 2 3 4 5]
flatten: [6 7 2 3 4 5]
original:
 [[6 1 2]
 [3 4 5]]


In [59]:
# リストの場合はコピー元は変わらない。
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print("list1:", py_list1)
print("list2:", py_list2)

list1: [0, 1]
list2: [2, 1]


In [62]:
# numpy adarrayの場合はコピー元も変わる。
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2
print("list1:", np_array1)
print("list2:", np_array2)

list1: [2 1]
list2: [2 1]


### 数列を返す

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# 同じ
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# range()と使い方は同じ。
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### 乱数

In [80]:
# 引数にはタプルを渡す必要がある。
f = np.random.random((3, 2))
f

array([[0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752],
       [0.34317802, 0.72904971]])

In [99]:
#乱数固定の方法 ↑のままだと実行するたびに値が変わる。
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [100]:
# 同一セル内に書く必要がある　or　直後の乱数にのみ適用している ⇒　同一セル内であれば同じだった。
np.random.random((3, 2))

array([[0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752],
       [0.34317802, 0.72904971]])

In [103]:
# 1以上10未満の整数を発生させる。
np.random.randint(1, 10)

1

In [105]:
# 1以上10未満の整数で3×3の配列を生成する。
np.random.randint(1, 10, (3, 3))

array([[5, 9, 1],
       [8, 4, 5],
       [7, 2, 6]])

In [111]:
# 小数点以下も含む場合
np.random.uniform(0, 5, size=(2, 3))

array([[0.60314333, 4.131704  , 3.01530064],
       [2.72534003, 1.71381917, 1.52060395]])

In [113]:
# 正規分布に従った乱数を発生させる （標準正規分布）
np.random.randn(4, 2)

array([[-0.77270871,  0.79486267],
       [ 0.31427199, -1.32626546],
       [ 1.41729905,  0.80723653],
       [ 0.04549008, -0.23309206]])

In [116]:
# 正規分布に従った乱数発生　（パラメータ指定）
np.random.normal(4, 10, size=(2, 2))

array([[ -0.03366038,   2.73970415],
       [ -4.37516723, -12.05962761]])

In [125]:
# 同じ要素の数列を作る 引数はタプル
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [126]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 単位行列

In [127]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 指定値で埋める

In [132]:
# 第一引数がサイズ、第二引数が値  np.piでも円周率が出せる。
np.full((3, 3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [133]:
# nan値
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

### 範囲指定で均等割りデータを作る

In [134]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [135]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

### 要素間の差分

In [138]:
# 要素前後の差分が計算されている。
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

### 連結

In [144]:
a = np.array([1, 2, 3])
a1 = np. array([4, 5, 6])
np.concatenate((a, a1))  # np.concatenate([a, a1])でも○

array([1, 2, 3, 4, 5, 6])

In [148]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b1 = np.array([[10], [20]])
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [149]:
# ↑と同じ
np.hstack([b, b1])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [151]:
# 行を増やす
b2 = np.array([[7, 8, 9], [10, 11, 12]])
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 分割

In [157]:
# 列の分割
first, second = np.hsplit(b3, [2])
first

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [158]:
second

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [160]:
# 行の分割
first1, second1 = np.vsplit(b3, [2])
first1

array([[1, 2, 3],
       [4, 5, 6]])

In [161]:
second1

array([[ 7,  8,  9],
       [10, 11, 12]])

### 転置

In [162]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 次元追加

In [165]:
a

array([1, 2, 3])

In [166]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [167]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

### グリッドデータの生成

In [169]:
m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [171]:
n = np.arange(4, 7)
n

array([4, 5, 6])

In [172]:
xx, yy = np.meshgrid(m, n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [173]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

### Numpy の各機能

In [175]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [177]:
x.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
y = np.linspace(1, 100, 12)
y

array([  1.,  10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91.,
       100.])

### ユニバーサルファンクション