# ★Numpyについて

In [ ]:
# インポート
import numpy as np

### 1次元配列

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
print(a)

# 型
print(type(a))

# 一次元配列で要素が3つある
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


### 2次元配列

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 2行3列の配列
print(b.shape)

(2, 3)


### 変形

In [ ]:
c1 = np.array(range(6))
c1

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 2行3列の配列に変形
c2 = c1.reshape(2, 3) # ((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# もとに戻す
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [ ]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [ ]:
# お試し 変わらなかった…
cc1 = np.array([[1, 2, 3], [4, 5, 6]])
print("ravel:", cc1.ravel())
print("flatten:", cc1.flatten())

ravel: [1 2 3 4 5 6]
flatten: [1 2 3 4 5 6]


### データ型

In [ ]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [ ]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [ ]:
d.dtype

dtype('int16')

In [ ]:
# 型の変更
d.astype(np.float16)

array([1., 2.], dtype=float16)

### インデックスとスライス